[package]
name = "ref_exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
iso = { path = "../iso/" }
debug = { path = "../debug" }
bevy_egui = { workspace = true }
bevy_image_export = "0.13.0"
bevy_file_dialog = "0.8.0"
directories = "6.0.0"
